### ISSUE TITLE
Child size

### ISSUE THREAD

**Issue by BenNG** [camillo/TerminatorPlugins#1]
Is there a way to set the size of a child in the Layout plugin ?

**Comment by camillo** [comment]
Nopes, sorry.

As I wrote the plugin I was new to gtk and did not manage to set the (already stored) sizes. Perhaps I find time during the next days, to fix this.

**Comment by BenNG** [comment]
Ok !

thx for answering :)

**Comment by camillo** [comment]
I was not able to restore the positions. It works for simple layouts, but fails when things get complex. You  can try, if it helps you. New save files have a setSplitRatios attribute. Set it to true, and layoutmanager tries to restores the positions. Will not work on your old save files.
