### ISSUE TITLE
Keyboard inputs are not logged

### ISSUE THREAD

**Issue by julienisapunk** [camillo/TerminatorPlugins#2]
The "log terminal" function does not log keyboard inputs.

**Comment by camillo** [comment]
What exacty have you tried @julienisageek? I tested again and it works for me. Your logfile should be in /tmp if you did not configure an other target.

**Comment by julienisapunk** [comment]
Hi @camillo,

Thank you for your answer. What I meant is that the logfile contains the output of the commands, but not the commands themselve (what I called "keyboard inputs"). 

For instance, here is what I got in the terminal:

julien@tsuyoshi:~$ pwd
/home/julien
julien@tsuyoshi:~$ cd Desktop/
julien@tsuyoshi:~/Desktop$ ls -ltr
total 0
julien@tsuyoshi:~/Desktop$ cd ~
julien@tsuyoshi:~$ ls -ltr
total 32
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Videos
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Templates
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Public
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Music
drwxr-xr-x 3 julien julien 4096 Jul 29 20:27 Documents
drwxr-xr-x 2 julien julien 4096 Jul 29 20:27 Pictures
drwxr-xr-x 5 julien julien 4096 Aug 31 16:39 Downloads
drwxr-xr-x 2 julien julien 4096 Sep  3 11:01 Desktop

But here is what I get in the logfile:

/home/julien
julien@tsuyoshi:~$ 
julien@tsuyoshi:~/Desktop$ 
total 0
julien@tsuyoshi:~/Desktop$ 
julien@tsuyoshi:~$ 
total 32
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Videos
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Templates
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Public
drwxr-xr-x 2 julien julien 4096 Jul 13 22:08 Music
drwxr-xr-x 3 julien julien 4096 Jul 29 20:27 Documents
drwxr-xr-x 2 julien julien 4096 Jul 29 20:27 Pictures
drwxr-xr-x 5 julien julien 4096 Aug 31 16:39 Downloads
drwxr-xr-x 2 julien julien 4096 Sep  3 11:01 Desktop
julien@tsuyoshi:~$

As you can see, I'm missing all the command inputs.

**Comment by julienisapunk** [comment]
Hello @camillo,

Any idea why the commands are not to be found in the log?

**Comment by julienisapunk** [comment]
Hello @camillo,

Unfortunately I'm still struggling with this issue which prevents the script from recording my commands. As a consequence, most of the logs are not understandable because they are incomplete. Any idea how to fix this?

Thank you and regards,
Julien

**Comment by camillo** [comment]
Hey julienisageek,

sorry for not answering. I looked into this again and do not find a way to get the inputs from the vte terminal, without parsing the whole buffer. If you find any easier way to get this information, I will implemented it.

Possible that I will have some time to have a deeper look into this myself, but during the next 2 weeks I am pretty busy.

**Comment by camillo** [comment]
Hey julienisageek,
I fixed this. Prob is, that I get two change events (prompt and command) and cannot know if line is finished. I guess I will make a cleaner solution, but for now you see the prompt twice, since I log the line twice.

**Comment by julienisapunk** [comment]
Hello @camillo,
Understood. Thank you very much for the fix. I'll test it right away.
Cheers
