### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by krytarowski** [camillo/TerminatorPlugins#3]
Thank you for your great work!

Please tag TerminatorPlugins, so it can be easily packaged. I maintain -git snapshot for pkgsrc-wip on NetBSD. Lack of tag/release blocks putting it to the main pkgsrc repository and build binary packages.

http://pkgsrc.se/wip/py-terminator-plugins-git

**Comment by camillo** [comment]
Hey krytarowski!

would you please send me a link, where I can read what you need? Or do you really just want me to do create a git tag? Sorry, I am just coding and do not have much knowledge about releasing stuff.

**Comment by krytarowski** [comment]
Please tag (eg. git tag 1) the current version as it is and push to GitHub (git push origin 1).

Another solution is to push your plugins to upstream developers.

Thank you.

**Comment by camillo** [comment]
Ok. Have done that.
thx
