### ISSUE TITLE
suggestion: change log location

### ISSUE THREAD

**Issue by jringoot** [camillo/TerminatorPlugins#4]
This is a very cool plugin, I use it to log my work and study, to make documentation after implementations.
But my /tmp gets cleaned up at reboot, I am not sure if it is typical Ubuntu.
Thus I have change the path in the plugin from /tmp to /var/log/terminator:
DEFAULT_SETTINGS = {SETTING_DIR            : "/var/log/terminator",
                    SETTING_EXPORT_FILE    : "/var/log/terminator/.terminatorExports",

**Comment by camillo** [comment]
No need to change plugin's sources. You can configure this in the settings file. See docu:

Configuration
All configuration is done in terminator's config file (~/.config/terminator/config on my system).
Include a [[TerminalExporter]] section inside [plugins] section (see example at end of this file).
Options are:
- directory
  Default is /tmp.
  Exports and logs are written into this directory; no shortcuts like ~, $HOME etc are allowed.
  Content of your terminal may contain VERY SENSITIVE data. You probably do not want them inside /tmp.
  Make sure that configured directory exists.
