### ISSUE TITLE
Make LayoutManager compatible with Terminator 1.90 (gtk-3)

### ISSUE THREAD

**Issue by dmirtillo** [camillo/TerminatorPlugins#6]
Hi,
as terminator 1.9 is being pushed as stable in the official arch repo ( https://www.archlinux.org/packages/community/any/terminator/ ), the LayoutManager plugin is no longer working.
The error is the following:
`PluginRegistry::load_plugins: Importing plugin LayoutManager.py failed: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183`

**Comment by microdou** [comment]
[PR](https://github.com/camillo/TerminatorPlugins/pull/7).
